apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: box
  name: box
spec:
  volume:
  - name: log-volume
    emptyDir: {}
  initcontainers:
  - image: busybox
    name: busybox
    command:
    - /bin/sh
    - -c
    - "wget -O /work-dir/index.html http://neverssl.com/online"
    volumeMounts:
    - mountPath: /work-dir
      name: log-volume
  containers:
  - image: nginx
    name: box
    ports:
    - containerPort: 80
    resources: {}
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: log-volume
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
